# Generated by Django 5.2.3 on 2025-06-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_facecomparison_temp_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facecomparison',
            name='temp_passport',
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='temp_passport',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
